# Generated by Django 5.0.4 on 2024-04-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appri', '0003_alter_student_city_alter_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
